name: Update Visitor Count

on:
  push:
    branches:
      - main

jobs:
  update_count:
    runs-on: ubuntu-latest
    steps:
    - name: Increment Visitor Count
      run: |
        count=$(($(<count.txt) + 1))
        echo $count > count.txt
        git add count.txt
        git commit -m "Increment visitor count" count.txt
        git push